controller_list:
  - name: fake_robotic_leg_controller
    joints:
      - Rev22
      - Rev24
      - Rev26
      - Rev28
initial:  # Define initial robot poses.
  - group: robotic_leg
    pose: Home