robotleg:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  motor1_to_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 400, i: 20, d: 2}

  motor2_to_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 400, i: 20, d: 2}

  motor3_to_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 400, i: 20, d: 2}

  motor4_to_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 70, i: 20, d: 2}