controller_list:
  - name: fake_All_controller
    type: $(arg execution_type)
    joints:
      - joint1BackLeft
      - joint2BackLeft
      - joint3BackLeft
      - joint4BackLeft
      - joint1BackRight
      - joint2BackRight
      - joint3BackRight
      - joint4BackRight
      - joint1FrontLeft
      - joint2FrontLeft
      - joint3FrontLeft
      - joint4FrontLeft
      - joint1FrontRight
      - joint2FrontRight
      - joint3FrontRight
      - joint4FrontRight
  - name: fake_FrontLeft_controller
    type: $(arg execution_type)
    joints:
      - joint1FrontLeft
      - joint2FrontLeft
      - joint3FrontLeft
      - joint4FrontLeft
  - name: fake_FrontRight_controller
    type: $(arg execution_type)
    joints:
      - joint1FrontRight
      - joint2FrontRight
      - joint3FrontRight
      - joint4FrontRight
  - name: fake_BackLeft_controller
    type: $(arg execution_type)
    joints:
      - joint1BackLeft
      - joint2BackLeft
      - joint3BackLeft
      - joint4BackLeft
  - name: fake_BackRIght_controller
    type: $(arg execution_type)
    joints:
      - joint1BackRight
      - joint2BackRight
      - joint3BackRight
      - joint4BackRight
  - name: fake_FrontLegs_controller
    type: $(arg execution_type)
    joints:
      - joint1FrontLeft
      - joint2FrontLeft
      - joint3FrontLeft
      - joint4FrontLeft
      - joint1FrontRight
      - joint2FrontRight
      - joint3FrontRight
      - joint4FrontRight
  - name: fake_BackLegs_controller
    type: $(arg execution_type)
    joints:
      - joint1BackLeft
      - joint2BackLeft
      - joint3BackLeft
      - joint4BackLeft
      - joint1BackRight
      - joint2BackRight
      - joint3BackRight
      - joint4BackRight
initial:  # Define initial robot poses.
  - group: All
    pose: stabilaf
  - group: FrontLegs
    pose: doggy
  - group: BackLegs
    pose: sit