controller_list:
  - name: fake_front_left_controller
    type: $(arg execution_type)
    joints:
      - joint1FrontLeft
      - joint2FrontLeft
      - joint3FrontLeft
      - joint4FrontLeft
  - name: fake_front_right_controller
    type: $(arg execution_type)
    joints:
      - joint1FrontRight
      - joint2FrontRight
      - joint3FrontRight
      - joint4FrontRight
  - name: fake_back_left_controller
    type: $(arg execution_type)
    joints:
      - joint1BackLeft
      - joint2BackLeft
      - joint3BackLeft
      - joint4BackLeft
  - name: fake_back_right_controller
    type: $(arg execution_type)
    joints:
      - joint1BackRight
      - joint2BackRight
      - joint3BackRight
      - joint4BackRight
  - name: fake_all_controller
    type: $(arg execution_type)
    joints:
      - joint1BackLeft
      - joint2BackLeft
      - joint3BackLeft
      - joint4BackLeft
      - joint1BackRight
      - joint2BackRight
      - joint3BackRight
      - joint4BackRight
      - joint1FrontLeft
      - joint2FrontLeft
      - joint3FrontLeft
      - joint4FrontLeft
      - joint1FrontRight
      - joint2FrontRight
      - joint3FrontRight
      - joint4FrontRight
initial:  # Define initial robot poses.
#  - group: front_left
#    pose: home

  []