robotleg:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #Trajectory Controller
  robotleg_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - motor1_to_joint1
      - motor2_to_joint2
      - motor3_to_joint3
      - motor4_to_joint4
    
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      motor1_to_joint1:
        trajectory: 0.1
        goal: 0.1
      motor2_to_joint2:
        trajectory: 0.1
        goal: 0.1
      motor3_to_joint3:
        trajectory: 0.1
        goal: 0.1
      motor4_to_joint4:
        trajectory: 0.1
        goal: 0.1
    
    gains:
      motor1_to_joint1: {p: 200, i: 20, d: 5}
      motor2_to_joint2: {p: 200, i: 20, d: 5}
      motor3_to_joint3: {p: 200, i: 20, d: 5}
      motor4_to_joint4: {p: 50, i: 20, d: 5}

    state_publish_rate: 25
    action_monitor_rate: 10
    stop_trajectory_duration: 0.5