controller_list:
  - name: fake_FrontLeft_controller
    type: $(arg execution_type)
    joints:
      - joint1FrontLeft
      - joint2FrontLeft
      - joint3FrontLeft
      - joint4FrontLeft
  - name: fake_Front Right_controller
    type: $(arg execution_type)
    joints:
      - joint1FrontRight
      - joint2FrontRight
      - joint3FrontRight
      - joint4FrontRight
  - name: fake_BackLeft_controller
    type: $(arg execution_type)
    joints:
      - joint1BackLeft
      - joint2BackLeft
      - joint3BackLeft
      - joint4BackLeft
  - name: fake_BackRight_controller
    type: $(arg execution_type)
    joints:
      - joint1BackRight
      - joint2BackRight
      - joint3BackRight
      - joint4BackRight
initial:  # Define initial robot poses.
  - group: FrontLeft
    pose: HOME
  - group: Front Right
    pose: HOME
  - group: BackLeft
    pose: HOME
  - group: BackRight
    pose: HOME