# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: FrontLeft
  joint_model_group_pose: HOME
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1BackLeft
    - joint2BackLeft
    - joint3BackLeft
    - joint4BackLeft
    - joint1BackRight
    - joint2BackRight
    - joint3BackRight
    - joint4BackRight
    - joint1FrontLeft
    - joint2FrontLeft
    - joint3FrontLeft
    - joint4FrontLeft
    - joint1FrontRight
    - joint2FrontRight
    - joint3FrontRight
    - joint4FrontRight
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: FrontLeft_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1FrontLeft
      - joint2FrontLeft
      - joint3FrontLeft
      - joint4FrontLeft
  - name: Front Right_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1FrontRight
      - joint2FrontRight
      - joint3FrontRight
      - joint4FrontRight
  - name: BackLeft_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1BackLeft
      - joint2BackLeft
      - joint3BackLeft
      - joint4BackLeft
  - name: BackRight_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1BackRight
      - joint2BackRight
      - joint3BackRight
      - joint4BackRight
positionscontroller:
  type: effort_controllers/JointPositionController
  joints:
    []
  gains:
    {}