controller_list:
    - name: robotleg/robotleg_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints: [motor1_to_joint1, motor2_to_joint2, motor3_to_joint3, motor4_to_joint4]